name: Testing

on:
  pull_request:
    types: [closed]

jobs:
  remove_instance:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Saleor login
        uses: ./.github/actions/cli-login
        with:
          token: ${{ secrets.STAGING_TOKEN }}

      - name: Remove instance
        env:
          SALEOR_CLI_ENV: staging
        run: npx saleor env remove "${{ env.GITHUB_HEAD_REF_SLUG_URL }}" --force