name: Instance

on:
  pull_request:
    types: [closed]

jobs:
  remove_env:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Instance creation
        id: create_instance
        env:
          SALEOR_CLI_ENV: staging
        run: |
          echo "Create instance ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"